obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_X01BD/
obj-$(CONFIG_FOCALTECH_FP)	+= focaltech_X01BD/
obj-$(CONFIG_COMMON_FP_X00T)   += common_X00TD/
obj-$(CONFIG_CDFINGER_FP_X00T)	+= cdfinger_X00TD/
obj-$(CONFIG_GOODIX_FP_X00T)   += goodix_X00TD/
